# https://raw.githubusercontent.com/ivankatliarchuk/dotfiles/master/zsh/settings/starship.toml
# https://github.com/denysdovhan/spaceship-prompt/wiki/Presets

add_newline = false
[line_break]
disabled = false

[username]
disabled = true

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"

[directory]
truncation_length = 8

[docker_context]
symbol = "ğŸ‹ "

[env_var]
variable = "ENVIRONMENT"
style = "dimmed bold purple"

[git_status]
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨"
behind = "ğŸšœ"
diverged = "ğŸš¥"
# untracked = "ğŸ¤·â€"
stashed = "ğŸ“¦"
# modified = "ğŸ“"
staged.value = "++"
staged.style = "green"
staged_count.enabled = true
staged_count.style = "green"
renamed = "ğŸ‘…"
deleted = "ğŸ’¢"

[hostname]
ssh_only = true
format = "[$hostname]($style) in "
trim_at = ".companyname.com"
disabled = false

[kubernetes]
symbol = "â˜¸â›µ"
format = 'â˜¸[â›µ$context\($namespace\)](#2596BE) '
style = "green"
disabled = false

[python]
symbol = "î˜† "
pyenv_version_name = true
pyenv_prefix = "python "
format = '[${pyenv_prefix}${symbol} (${version} )(\($virtualenv\))]($style)'

[terraform]
symbol = "ğŸğŸ’¨ "

[aws]
style = "bold blue"
symbol = "ğŸ…° "
displayed_items = ""
disabled = true

[git_branch]
symbol = "ï˜ "

[git_commit]
commit_hash_length = 4
style = "bold green"
tag_symbol = "ğŸ· "

[nodejs]
symbol = "ï¢˜ "
format = "node [$symbol$version]($style) "
style = "#abdbe3"
detect_files = ["package.json", ".node-version", ".nvrc"]

[vagrant]
disabled = true
